
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests dishes and customization options.
 *
 * - suggestItems - A function that suggests dishes and customization options.
 * - SuggestItemsInput - The input type for the suggestItems function.
 * - SuggestItemsOutput - The return type for the suggestItems function.
 */

import {ai} from '@/ai/config';
import {z} from 'genkit';

const SuggestItemsInputSchema = z.object({
  menu: z.string().describe('The available menu items, as a JSON string.'),
  orderHistory: z
    .string()
    .describe('The order history of the user, as a JSON string.'),
  preferences: z
    .string()
    .describe('The preferences of the user, as a JSON string.'),
  vendorUsername: z
    .string()
    .optional()
    .describe('The username of the vendor for whom to suggest items. If not provided, suggest from the entire menu.'),
});
export type SuggestItemsInput = z.infer<typeof SuggestItemsInputSchema>;

const SuggestItemsOutputSchema = z.object({
  suggestions: z
    .array(z.object({ name: z.string() }))
    .describe('An array of objects, where each object represents a suggested dish and has a "name" key.'),
});
export type SuggestItemsOutput = z.infer<typeof SuggestItemsOutputSchema>;

export async function suggestItems(input: SuggestItemsInput): Promise<SuggestItemsOutput> {
  return suggestItemsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestItemsPrompt',
  input: {schema: SuggestItemsInputSchema},
  output: {schema: SuggestItemsOutputSchema},
  prompt: `You are a culinary expert specializing in suggesting dishes and customization options based on order history and preferences.

You will use this information to suggest dishes to the user.

Available Menu: {{{menu}}}
Order History: {{{orderHistory}}}
Preferences: {{{preferences}}}
{{#if vendorUsername}}
You MUST only suggest items from the vendor with username: {{{vendorUsername}}}.
{{/if}}

Based on the user's history and preferences, suggest a few items from the available menu.
You MUST only suggest items that are present in the "Available Menu".
Return a JSON object with a "suggestions" key. The value should be an array of objects, where each object has a "name" key with the exact name of the suggested dish from the menu.
Your response MUST be a valid JSON object and nothing else.
For example: {"suggestions": [{"name": "Plasma-Charred Burger"}, {"name": "Cryo-Grown Salad"}]}
Do not include any other text, explanation, or markdown formatting in your response.`,
});

const suggestItemsFlow = ai.defineFlow(
  {
    name: 'suggestItemsFlow',
    inputSchema: SuggestItemsInputSchema,
    outputSchema: SuggestItemsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
